# Generated by Django 5.1.1 on 2024-09-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=50)),
                ('game_name', models.CharField(max_length=255)),
                ('player_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddIndex(
            model_name='playercount',
            index=models.Index(fields=['game_name'], name='Trends_play_game_na_223146_idx'),
        ),
        migrations.AddIndex(
            model_name='playercount',
            index=models.Index(fields=['timestamp'], name='Trends_play_timesta_1761fa_idx'),
        ),
    ]
